#ifndef _TGT_AP_GPIO_SETTING_H_
#define _TGT_AP_GPIO_SETTING_H_

#define _TGT_AP_GPIO_TOUCH_RESET        GPIO_A17
#define _TGT_AP_GPIO_TOUCH_IRQ          GPIO_A1

#define _TGT_AP_GPIO_MMC_HOTPLUG	GPIO_A2

#define _TGT_AP_GPIO_CAM_RESET		GPIO_B1
#define _TGT_AP_GPIO_CAM_PWDN0		GPIO_B2 //Back
#define _TGT_AP_GPIO_CAM_PWDN1		GPO_0   //Front
//#define _TGT_AP_GPIO_CAM_FLASH
//#define _TGT_AP_GPIO_CAM_EN

#define _TGT_AP_GPIO_LCD_EN             GPIO_B4
#define _TGT_AP_GPIO_LCD_RESET          GPO_3

#define _TGT_AP_GPIO_HEADSET_DETECT     GPIO_A0


#define _TGT_AP_GPIO_VOLUME_UP          GPIO_D6
#define _TGT_AP_GPIO_VOLUME_DOWN        GPIO_D5

#define _TGT_AP_GPIO_WIFI               GPIO_A7
#define _TGT_AP_GPIO_BT_HOST_WAKE       GPIO_A5//GPIO_MAX_NUM

#define _TGT_AP_GPIO_USB_ID		GPIO_A4
#define _TGT_AP_GPIO_USB_VBUS_SWITCH	GPIO_A6
#endif // _TGT_AP_GPIO_SETTING_H_

