#ifndef _TGT_AP_GPIO_SETTING_H_
#define _TGT_AP_GPIO_SETTING_H_

#define _TGT_AP_GPIO_TOUCH_RESET        GPIO_B3
#define _TGT_AP_GPIO_TOUCH_IRQ          GPIO_A1

#define _TGT_AP_GPIO_MMC_HOTPLUG	GPIO_B1

#define _TGT_AP_GPIO_LCD_PWR            GPO_2

//#define _TGT_AP_GPIO_CAM_RESET
//#define _TGT_AP_GPIO_CAM_PWDN0
#define _TGT_AP_GPIO_CAM_PWDN1		GPO_1
#define _TGT_AP_GPIO_CAM_FLASH		GPIO_B0
//#define _TGT_AP_GPIO_CAM_EN

#define _TGT_AP_GPIO_LCD_RESET          GPO_3

#define _TGT_AP_GPIO_HEADSET_DETECT     GPIO_A0

#define _TGT_AP_GPIO_USB_DETECT         GPIO_NONE

#define _TGT_AP_GPIO_VOLUME_UP          GPIO_D6
#define _TGT_AP_GPIO_VOLUME_DOWN        GPIO_D5

#define _TGT_AP_GPIO_WIFI               GPIO_B2
#define _TGT_AP_GPIO_BT_HOST_WAKE       GPIO_B4

#define _TGT_AP_GPIO_USB_ID             GPIO_A4
#define _TGT_AP_GPIO_USB_VBUS_SWITCH    GPIO_A17

#endif // _TGT_AP_GPIO_SETTING_H_

