#ifndef _TGT_AP_GPIO_SETTING_H_
#define _TGT_AP_GPIO_SETTING_H_

#define _TGT_AP_GPIO_TOUCH_RESET        GPIO_A17
#define _TGT_AP_GPIO_TOUCH_IRQ          GPIO_A1

#define _TGT_AP_GPIO_CAM_RESET		GPO_0
#define _TGT_AP_GPIO_CAM_PWDN0		GPO_1
#define _TGT_AP_GPIO_CAM_PWDN1		GPIO_B4
//#define _TGT_AP_GPIO_CAM_FLASH
//#define _TGT_AP_GPIO_CAM_EN

#define _TGT_AP_GPIO_LCD_RESET          GPO_3

#define _TGT_AP_GPIO_LCD_PWR            GPIO_B3
//#define _TGT_AP_GPIO_LCD_EXTEN          GPIO_B9

#define _TGT_AP_GPIO_EXT_BL_ON          GPIO_B1

#define _TGT_AP_GPIO_HEADSET_DETECT     GPIO_A0
#define _TGT_AP_GPIO_CAM_FLASH		    GPIO_B2


#define _TGT_AP_GPIO_VOLUME_UP          GPIO_D6
#define _TGT_AP_GPIO_VOLUME_DOWN        GPIO_D5

#define _TGT_AP_GPIO_WIFI               GPIO_A4
#define _TGT_AP_GPIO_BT_HOST_WAKE       GPIO_A5

#define _TGT_AP_GPIO_USB_ID				GPIO_A7
#define _TGT_AP_GPIO_USB_VBUS_SWITCH	GPIO_A6
#endif // _TGT_AP_GPIO_SETTING_H_
