#ifndef _TGT_AP_GPIO_SETTING_H_
#define _TGT_AP_GPIO_SETTING_H_

#define _TGT_AP_GPIO_TOUCH_RESET        GPO_2
#define _TGT_AP_GPIO_TOUCH_IRQ          GPIO_B3

//LuoShuli 2014/10/13
#define _TGT_AP_GPIO_CAM_PWDN0		GPIO_A4
//#define _TGT_AP_GPIO_CAM_PWDN1		GPIO_B4

#define _TGT_AP_GPIO_LCD_RESET          GPO_3

#define _TGT_AP_GPIO_HEADSET_DETECT     GPIO_A0


#define _TGT_AP_GPIO_VOLUME_UP          GPIO_D6
#define _TGT_AP_GPIO_VOLUME_DOWN        GPIO_D5

#define _TGT_AP_GPIO_WIFI               GPIO_B2
#define _TGT_AP_GPIO_BT_HOST_WAKE       GPIO_B1

#define _TGT_AP_GPIO_USB_ID		GPIO_B5
#define _TGT_AP_GPIO_USB_VBUS_SWITCH	GPIO_A6
//#define _TGT_AP_GPIO_USB_VBUS_SWITCH	GPIO_A17
#endif // _TGT_AP_GPIO_SETTING_H_
