////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//            Copyright (C) 2003-2010, Coolsand Technologies, Inc.            //
//                            All Rights Reserved                             //
//                                                                            //
//      This source code is the property of Coolsand Technologies and is      //
//      confidential.  Any  modification, distribution,  reproduction or      //
//      exploitation  of  any content of this file is totally forbidden,      //
//      except  with the  written permission  of  Coolsand Technologies.      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  $HeadURL:http://svn.rdamicro.com/svn/developing1/Sources/platform/trunk/calib/src/calibp_audio_defaults.h$                                                                 //
//	$Author:zhihaozhu $                                                       //
//	$Date: 2016-02-25 11:31:44 +0800 (??, 25 ?? 2016)$                        //
//	$Revision: 29394$                                                         //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
//                                                                            //
/// @file calibp_audio_defaults.h                                             //
/// This file defines the calibration parameters for Audio                    //
//  It was created by the CAT tool,PLEASE DO NOT EDIT !!!                     //
////////////////////////////////////////////////////////////////////////////////

#ifndef  _CALIBP_AUDIO_DEFAULTS_H_
#define  _CALIBP_AUDIO_DEFAULTS_H_

#include "hal_rda_abb.h"

//  --------------------------------------------------
// DEFAULT_AUDIO_CALIB_PARAM_USED indicates that the file contains the
// default audio calibration parameters, which are NOT generated by
// the audio calibration tool.
// On the other hand, the file generated by the audio calibration tool
// should NOT contain this macro.

#define DEFAULT_AUDIO_CALIB_PARAM_USED
//  --------------------------------------------------
//  ----- Common calibration parameters.

#define DEFAULT_CALIB_CHIP_ID  CHIP_ASIC_ID
#if (CHIP_ASIC_ID == CHIP_ASIC_ID_GALLITE)
#if defined(GALLITE_IS_8805)
#define DEFAULT_CALIB_CHIP_DIE 8805
#elif defined(GALLITE_IS_8806)
#define DEFAULT_CALIB_CHIP_DIE 8806
#endif
#endif  // Gallite

#define DEFAULT_CALIB_VERSION CALIB_VERSION_NUMBER

//HandSet Mode

/// 假设 CALIB_BUFFER_T calib_t;
///每个宏对应的是 itf
/// HS   0
/// EP   1
/// LS   2
/// BT   3
/// FM   4
/// TV   5

///  Audio params, MDF profile.
///calib_t.audio_voc.voc[itf].fir.mdfFilter
#define DEFAULT_CALIB_MDF_PROFILE_HS { 0x4000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000}

///  Audio params, SDF profile.
/// calib_t.audio_voc.voc[itf].fir.sdfFilter
#define DEFAULT_CALIB_SDF_PROFILE_HS { 0x4000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000}

///  Audio params, MDF profile.
#define DEFAULT_CALIB_MDF_PROFILE_EP { 0x4000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000}
///  Audio params, SDF profile.
#define DEFAULT_CALIB_SDF_PROFILE_EP { 0x4000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000}

///  Audio params,MDF profile.
#define DEFAULT_CALIB_MDF_PROFILE_LS { 0x4000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000}

///  Audio params,SDF profile.
#define DEFAULT_CALIB_SDF_PROFILE_LS { 0x4000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000}

///  Audio params, MDF profile.
#define DEFAULT_CALIB_MDF_PROFILE_BT { 0x4000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000}
///  Audio params, SDF profile.
#define DEFAULT_CALIB_SDF_PROFILE_BT { 0x4000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000}

///  Audio params,MDF profile.
#define DEFAULT_CALIB_MDF_PROFILE_FM { 0x4000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000}

///  Audio params,SDF profile.
#define DEFAULT_CALIB_SDF_PROFILE_FM { 0x4000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000, \
				0x0000, 0x0000, 0x0000, 0x0000}

///  Audio params, MDF profile.
#define DEFAULT_CALIB_MDF_PROFILE_TV { 0x4000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000}
///  Audio params, SDF profile.
#define DEFAULT_CALIB_SDF_PROFILE_TV { 0x4000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000, \
		0x0000, 0x0000, 0x0000, 0x0000}

#define DEFAULT_CALIB_AUDIO_VOC_RESERVE { 0x00000000, 0x00000000, 0x00000000, 0x00000000, \
		0x00000000, 0x00000000, 0x00000000, 0x00000000, \
		0x00000000, 0x00000000, 0x00000000, 0x00000000, \
		0x00000000, 0x00000000, 0x00000000, 0x00000000, \
		0x00000000, 0x00000000, 0x00000000, 0x00000000, \
		0x00000000, 0x00000000, 0x00000000, 0x00000000, \
		0x00000000, 0x00000000, 0x00000000, 0x00000000, \
		0x00000000, 0x00000000, 0x00000000, 0x00000000, \
		0x00000000, 0x00000000, 0x00000000, 0x00000000, \
		0x00000000, 0x00000000, 0x00000000, 0x00000000, \
		0x00000000, 0x00000000, 0x00000000, 0x00000000, \
		0x00000000, 0x00000000, 0x00000000, 0x00000000, \
		0x00000000, 0x00000000, 0x00000000, 0x00000000, \
		0x00000000, 0x00000000, 0x00000000, 0x00000000, \
		0x00000000, 0x00000000, 0x00000000, 0x00000000, \
		0x00000000, 0x00000000, 0x00000000, 0x00000000}
/// calib_t.bb.audio[itf].audioParams

#define DEFAULT_CALIB_AUDIO_HS_PARAMS          { 0,0,0,0,0,50,0,8,127,0,0,0,0,{0,0,0,0}}
#define DEFAULT_CALIB_AUDIO_EP_PARAMS          { 0,0,0,0,0,50,0,8,127,0,0,0,0,{0,0,0,0}}
#define DEFAULT_CALIB_AUDIO_LS_PARAMS          { 0,0,0,0,0,40,1,0,127,0,0,0,0,{0,0,0,0}}
#define DEFAULT_CALIB_AUDIO_BT_PARAMS          { 0,0,0,0,0,50,0,8,127,0,0,0,0,{0,0,0,0}}
#define DEFAULT_CALIB_AUDIO_FM_PARAMS          { 0,0,0,0,0,50,0,8,127,0,0,0,0,{0,0,0,0}}
#define DEFAULT_CALIB_AUDIO_TV_PARAMS          { 0,0,0,0,0,50,0,8,127,0,0,0,0,{0,0,0,0}}

// Echo Cancel params. EC Alg is for HS. In LS mode, EC will NOT be enabled.
/// calib_t.bb.audio[itf].vocEc
//HS
#define DEFAULT_EC_HS_MU    3
#define DEFAULT_EC_HS_REL   1
#define DEFAULT_EC_HS_MIN   7
#define DEFAULT_ES_HS_ON    0
#define DEFAULT_ES_HS_DTD   0
#define DEFAULT_ES_HS_VAD   0

//EP
#define DEFAULT_EC_EP_MU    0
#define DEFAULT_EC_EP_REL   0
#define DEFAULT_EC_EP_MIN   0
#define DEFAULT_ES_EP_ON    0
#define DEFAULT_ES_EP_DTD   0
#define DEFAULT_ES_EP_VAD   0

//LS
#define DEFAULT_EC_LS_MU    0
#define DEFAULT_EC_LS_REL   0
#define DEFAULT_EC_LS_MIN   0
#define DEFAULT_ES_LS_ON    1
#define DEFAULT_ES_LS_DTD   0
#define DEFAULT_ES_LS_VAD   8


//BT
#define DEFAULT_EC_BT_MU    3
#define DEFAULT_EC_BT_REL   2
#define DEFAULT_EC_BT_MIN   3
#define DEFAULT_ES_BT_ON    0
#define DEFAULT_ES_BT_DTD   0
#define DEFAULT_ES_BT_VAD   0

//FM
#define DEFAULT_EC_FM_MU    0
#define DEFAULT_EC_FM_REL   0
#define DEFAULT_EC_FM_MIN   0
#define DEFAULT_ES_FM_ON    1
#define DEFAULT_ES_FM_DTD   0
#define DEFAULT_ES_FM_VAD   8

//TV
#define DEFAULT_EC_TV_MU    0
#define DEFAULT_EC_TV_REL   0
#define DEFAULT_EC_TV_MIN   0
#define DEFAULT_ES_TV_ON    1
#define DEFAULT_ES_TV_DTD   0
#define DEFAULT_ES_TV_VAD   8




#define DEFAULT_NA        0

///  Audio Enable params, for the handset
#define DEFAULT_ENABLE_HANDSET              CALIB_SDF_ON | CALIB_MDF_ON
///  Audio Enable params, for the earpiece
#define DEFAULT_ENABLE_EARPIECE             CALIB_SDF_ON | CALIB_MDF_ON
///  Audio Enable params, for the loudspeaker
#define DEFAULT_ENABLE_LOUDSPEAKER          CALIB_SDF_ON | CALIB_MDF_ON | CALIB_EC_ON

/// Audio VoC parameters.
#define DEFAULT_CALIB_AUDIO_VOC_HS_EC       { DEFAULT_EC_HS_MU, DEFAULT_EC_HS_REL, DEFAULT_EC_HS_MIN, DEFAULT_ES_HS_ON, DEFAULT_ES_HS_DTD, DEFAULT_ES_HS_VAD, DEFAULT_ENABLE_HANDSET}

#define DEFAULT_CALIB_AUDIO_VOC_HS_FILTERS  { 1, 1, DEFAULT_CALIB_MDF_PROFILE_HS, DEFAULT_CALIB_SDF_PROFILE_HS }

#define DEFAULT_CALIB_AUDIO_VOC_EP_EC       { DEFAULT_EC_EP_MU, DEFAULT_EC_EP_REL, DEFAULT_EC_EP_MIN, DEFAULT_ES_EP_ON, DEFAULT_ES_EP_DTD, DEFAULT_ES_EP_VAD, DEFAULT_ENABLE_EARPIECE}

#define DEFAULT_CALIB_AUDIO_VOC_EP_FILTERS  { 1, 1, DEFAULT_CALIB_MDF_PROFILE_EP, DEFAULT_CALIB_SDF_PROFILE_EP }

#define DEFAULT_CALIB_AUDIO_VOC_LS_EC       { DEFAULT_EC_LS_MU, DEFAULT_EC_LS_REL, DEFAULT_EC_LS_MIN, DEFAULT_ES_LS_ON, DEFAULT_ES_LS_DTD, DEFAULT_ES_LS_VAD, DEFAULT_ENABLE_LOUDSPEAKER}

#define DEFAULT_CALIB_AUDIO_VOC_LS_FILTERS  { 1, 1, DEFAULT_CALIB_MDF_PROFILE_LS, DEFAULT_CALIB_SDF_PROFILE_LS }

/// Audio VoC parameters.
#define DEFAULT_CALIB_AUDIO_VOC_BT_EC       { DEFAULT_EC_BT_MU, DEFAULT_EC_BT_REL, DEFAULT_EC_BT_MIN, DEFAULT_ES_BT_ON, DEFAULT_ES_BT_DTD, DEFAULT_ES_BT_VAD, DEFAULT_ENABLE_HANDSET}

#define DEFAULT_CALIB_AUDIO_VOC_BT_FILTERS  { 1, 1, DEFAULT_CALIB_MDF_PROFILE_BT, DEFAULT_CALIB_SDF_PROFILE_BT }

#define DEFAULT_CALIB_AUDIO_VOC_FM_EC       { DEFAULT_EC_FM_MU, DEFAULT_EC_FM_REL, DEFAULT_EC_FM_MIN, DEFAULT_ES_FM_ON, DEFAULT_ES_FM_DTD, DEFAULT_ES_FM_VAD, DEFAULT_ENABLE_LOUDSPEAKER}

#define DEFAULT_CALIB_AUDIO_VOC_FM_FILTERS  { 1, 1, DEFAULT_CALIB_MDF_PROFILE_FM, DEFAULT_CALIB_SDF_PROFILE_FM }

#define DEFAULT_CALIB_AUDIO_VOC_TV_EC       { DEFAULT_EC_TV_MU, DEFAULT_EC_TV_REL, DEFAULT_EC_TV_MIN, DEFAULT_ES_TV_ON, DEFAULT_ES_TV_DTD, DEFAULT_ES_TV_VAD, DEFAULT_ENABLE_LOUDSPEAKER}

#define DEFAULT_CALIB_AUDIO_VOC_TV_FILTERS  { 1, 1, DEFAULT_CALIB_MDF_PROFILE_TV, DEFAULT_CALIB_SDF_PROFILE_TV }

#if (CHIP_ASIC_ID == CHIP_ASIC_ID_GALLITE || \
     CHIP_ASIC_ID == CHIP_ASIC_ID_8808)
/// Default audio output gains for handset.
/// calib_t.bb.audio[itf].audioGains.outGains
#define DEFAULT_CALIB_AUDIO_OUT_HS  \
 {\
  {  0, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0,  0, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0 }, \
  {  0, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0,  0, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0 }, \
  {  3, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0,  3, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0 }, \
  {  6, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0,  6, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0 }, \
  {  9, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0,  9, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0 }, \
  { 12, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0, 12, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0 }, \
  { 15, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0, 15, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0 }, \
  { 21, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0, 21, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0 }, \
 }

/// Default audio output gains for ear-piece.
#define DEFAULT_CALIB_AUDIO_OUT_EP  \
 {\
  {  0, DEFAULT_ABB_DAC_GAIN_HEAD  , 0, 0,  0, DEFAULT_ABB_DAC_GAIN_HEAD  , 0, 0 }, \
  {  0, DEFAULT_ABB_DAC_GAIN_HEAD-3, 0, 0,  0, DEFAULT_ABB_DAC_GAIN_HEAD-3, 0, 0 }, \
  {  0, DEFAULT_ABB_DAC_GAIN_HEAD  , 0, 0,  0, DEFAULT_ABB_DAC_GAIN_HEAD  , 0, 0 }, \
  {  3, DEFAULT_ABB_DAC_GAIN_HEAD  , 0, 0,  3, DEFAULT_ABB_DAC_GAIN_HEAD  , 0, 0 }, \
  {  6, DEFAULT_ABB_DAC_GAIN_HEAD  , 0, 0,  6, DEFAULT_ABB_DAC_GAIN_HEAD  , 0, 0 }, \
  {  9, DEFAULT_ABB_DAC_GAIN_HEAD  , 0, 0,  9, DEFAULT_ABB_DAC_GAIN_HEAD  , 0, 0 }, \
  { 12, DEFAULT_ABB_DAC_GAIN_HEAD  , 0, 0, 12, DEFAULT_ABB_DAC_GAIN_HEAD  , 0, 0 }, \
  { 15, DEFAULT_ABB_DAC_GAIN_HEAD  , 0, 0, 15, DEFAULT_ABB_DAC_GAIN_HEAD  , 0, 0 }, \
 }

/// Default audio output gains for loud-speaker
#define DEFAULT_CALIB_AUDIO_OUT_LS \
  {\
  {  0, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0,  0, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  {  0, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0,  0, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  {  3, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0,  3, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  {  6, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0,  6, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  {  9, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0,  9, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  { 12, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0, 12, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  { 12, DEFAULT_ABB_DAC_GAIN_SPEAKER, 3, 0, 15, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  { 12, DEFAULT_ABB_DAC_GAIN_SPEAKER, 6, 0, 21, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
 }

/// Default audio output gains for BT.
#define DEFAULT_CALIB_AUDIO_OUT_BT  \
 {\
  { 0, 0, 0, 0, 0, 0, 0, 0 }, \
  { 0, 0, 0, 0, 0, 0, 0, 0 }, \
  { 0, 0, 0, 0, 0, 0, 0, 0 }, \
  { 0, 0, 0, 0, 0, 0, 0, 0 }, \
  { 0, 0, 0, 0, 0, 0, 0, 0 }, \
  { 0, 0, 0, 0, 0, 0, 0, 0 }, \
  { 0, 0, 0, 0, 0, 0, 0, 0 }, \
  { 0, 0, 0, 0, 0, 0, 0, 0 }, \
 }

/// Default audio output gains for FM
#define DEFAULT_CALIB_AUDIO_OUT_FM \
 {\
  {  0, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0,  0, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  {  0, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0,  0, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  {  3, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0,  3, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  {  6, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0,  6, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  {  9, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0,  9, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  { 12, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0, 12, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  { 15, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0, 15, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  { 21, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0, 21, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
 }

/// Default audio output gains for analog TV
#define DEFAULT_CALIB_AUDIO_OUT_TV \
 {\
  {  0, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0,  0, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  {  0, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0,  0, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  {  3, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0,  3, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  {  6, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0,  6, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  {  9, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0,  9, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  { 12, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0, 12, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  { 15, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0, 15, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  { 21, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0, 21, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
 }
#else // 8809 or later

#if (AUDIO_CALIB_VER != 1)
/// Default audio output gains for handset.
#define DEFAULT_CALIB_AUDIO_OUT_HS  \
 {\
  {  0, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0,  0, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0 }, \
  {  0, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0,  0, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0 }, \
  {  3, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0,  3, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0 }, \
  {  6, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0,  6, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0 }, \
  {  9, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0,  9, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0 }, \
  { 12, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0, 12, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0 }, \
  { 15, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0, 15, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0 }, \
  { 18, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0, 21, DEFAULT_ABB_DAC_GAIN_RECEIVER, 0, 0 }, \
 }

/// Default audio output gains for ear-piece.
#define DEFAULT_CALIB_AUDIO_OUT_EP  \
 {\
  {  0, DEFAULT_ABB_DAC_GAIN_HEAD   , 0, 0,  0, DEFAULT_ABB_DAC_GAIN_HEAD   , 0, 0 }, \
  {  0, DEFAULT_ABB_DAC_GAIN_HEAD-12, 0, 0,  0, DEFAULT_ABB_DAC_GAIN_HEAD-12, 0, 0 }, \
  {  0, DEFAULT_ABB_DAC_GAIN_HEAD-9 , 0, 0,  0, DEFAULT_ABB_DAC_GAIN_HEAD-9 , 0, 0 }, \
  {  0, DEFAULT_ABB_DAC_GAIN_HEAD-6 , 0, 0,  0, DEFAULT_ABB_DAC_GAIN_HEAD-6 , 0, 0 }, \
  {  0, DEFAULT_ABB_DAC_GAIN_HEAD-3 , 0, 0,  0, DEFAULT_ABB_DAC_GAIN_HEAD-3 , 0, 0 }, \
  {  0, DEFAULT_ABB_DAC_GAIN_HEAD   , 0, 0,  0, DEFAULT_ABB_DAC_GAIN_HEAD   , 0, 0 }, \
  {  3, DEFAULT_ABB_DAC_GAIN_HEAD   , 0, 0,  3, DEFAULT_ABB_DAC_GAIN_HEAD   , 0, 0 }, \
  {  6, DEFAULT_ABB_DAC_GAIN_HEAD   , 0, 0,  6, DEFAULT_ABB_DAC_GAIN_HEAD   , 0, 0 }, \
 }

/// Default audio output gains for loud-speaker
#define DEFAULT_CALIB_AUDIO_OUT_LS \
  {\
  {  0, DEFAULT_ABB_DAC_GAIN_SPEAKER,   0, 0,  0, DEFAULT_ABB_DAC_GAIN_SPEAKER,   0, 0 }, \
  { -2, DEFAULT_ABB_DAC_GAIN_SPEAKER,   0, 0, -2, DEFAULT_ABB_DAC_GAIN_SPEAKER,   0, 0 }, \
  { 10, DEFAULT_ABB_DAC_GAIN_SPEAKER-9, 0, 0, 10, DEFAULT_ABB_DAC_GAIN_SPEAKER-6, 0, 0 }, \
  { 10, DEFAULT_ABB_DAC_GAIN_SPEAKER-6, 0, 0, 10, DEFAULT_ABB_DAC_GAIN_SPEAKER-3, 0, 0 }, \
  { 10, DEFAULT_ABB_DAC_GAIN_SPEAKER-3, 0, 0, 10, DEFAULT_ABB_DAC_GAIN_SPEAKER,   0, 0 }, \
  { 10, DEFAULT_ABB_DAC_GAIN_SPEAKER,   0, 0, 16, DEFAULT_ABB_DAC_GAIN_SPEAKER,   0, 0 }, \
  { 16, DEFAULT_ABB_DAC_GAIN_SPEAKER,   0, 0, 19, DEFAULT_ABB_DAC_GAIN_SPEAKER,   0, 0 }, \
  { 19, DEFAULT_ABB_DAC_GAIN_SPEAKER,   0, 0, 21, DEFAULT_ABB_DAC_GAIN_SPEAKER,   0, 0 }, \
 }

/// Default audio output gains for BT.
#define DEFAULT_CALIB_AUDIO_OUT_BT  \
{\
{0, 0, 0, 0, 0, 0, 0, 0},\
{0, 0, 0, 0, 0, 0, 0, 0},\
{0, 0, 0, 0, 0, 0, 0, 0},\
{0, 0, 0, 0, 0, 0, 0, 0},\
{0, 0, 0, 0, 0, 0, 0, 0},\
{0, 0, 0, 0, 0, 0, 0, 0},\
{0, 0, 0, 0, 0, 0, 0, 0},\
{0, 0, 0, 0, 0, 0, 0, 0},\
}
/// Default audio output gains for FM.
#define DEFAULT_CALIB_AUDIO_OUT_FM \
 {\
  {  0, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0,  0, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  {  0, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0, -2, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  {  3, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0, 10, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  {  6, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0, 16, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  {  9, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0, 19, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  { 12, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0, 21, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  { 15, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0, 22, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  { 21, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0, 23, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
 }

/// Default audio output gains for analog TV
#define DEFAULT_CALIB_AUDIO_OUT_TV \
 {\
  {  0, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0,  0, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  {  0, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0, -2, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  {  3, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0, 10, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  {  6, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0, 16, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  {  9, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0, 19, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  { 12, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0, 21, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  { 15, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0, 22, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
  { 21, DEFAULT_ABB_DAC_GAIN_HEAD, 0, 0, 23, DEFAULT_ABB_DAC_GAIN_SPEAKER, 0, 0 }, \
 }

#else // AUDIO_CALIB_VER == 1
/// Default audio output gains for handset.
#define DEFAULT_CALIB_AUDIO_OUT_HS \
{\
   {9, -2, 0, 0, 21, -2, 0, 0}, \
   {9, -2, -18, 0, 21, -2, -18, 0}, \
   {9, -2, -15, 0, 21, -2, -15, 0}, \
   {9, -2, -12, 0, 21, -2, -12, 0}, \
   {9, -2, -9, 0, 21, -2, -9, 0}, \
   {9, -2, -6, 0, 21, -2, -6, 0}, \
   {9, -2, -3, 0, 21, -2, -3, 0}, \
   {9, -2, 0, 0, 21, -2, 0, 0}, \
}

/// Default audio output gains for ear-piece.
#define DEFAULT_CALIB_AUDIO_OUT_EP \
{\
   {12, -2, 0, 0, 6, -2, 0, 0}, \
   {12, -2, -18, 0, 6, -2, -18, 0}, \
   {12, -2, -15, 0, 6, -2, -15, 0}, \
   {12, -2, -12, 0, 6, -2, -12, 0}, \
   {12, -2, -9, 0, 6, -2, -9, 0}, \
   {12, -2, -6, 0, 6, -2, -6, 0}, \
   {12, -2, -3, 0, 6, -2, -3, 0}, \
   {12, -2, 0, 0, 6, -2, 0, 0}, \
}

/// Default audio output gains for loud-speaker.
#define DEFAULT_CALIB_AUDIO_OUT_LS \
{\
   {12, -2, 0, 0, 18, -2, 0, 0}, \
   {12, -2, -18, 0, 18, -2, -18, 0}, \
   {12, -2, -15, 0, 18, -2, -15, 0}, \
   {12, -2, -12, 0, 18, -2, -12, 0}, \
   {12, -2, -9, 0, 18, -2, -9, 0}, \
   {12, -2, -6, 0, 18, -2, -6, 0}, \
   {12, -2, -3, 0, 18, -2, -3, 0}, \
   {12, -2, 0, 0, 18, -2, 0, 0}, \
}

/// Default audio output gains for BT.
#define DEFAULT_CALIB_AUDIO_OUT_BT \
{\
   {0, 0, -21, 0, 0, 0, -21, 0}, \
   {0, 0, -18, 0, 0, 0, -18, 0}, \
   {0, 0, -15, 0, 0, 0, -15, 0}, \
   {0, 0, -12, 0, 0, 0, -12, 0}, \
   {0, 0, -9, 0, 0, 0, -9, 0}, \
   {0, 0, -6, 0, 0, 0, -6, 0}, \
   {0, 0, -3, 0, 0, 0, -3, 0}, \
   {0, 0, 0, 0, 0, 0, 0, 0}, \
}

/// Default audio output gains for FM.
#define DEFAULT_CALIB_AUDIO_OUT_FM \
{\
   {0, -2, 0, 0, 2, -2, 0, 0}, \
   {3, -2, -18, 0, 5, -2, -18, 0}, \
   {6, -2, -15, 0, 8, -2, -15, 0}, \
   {9, -2, -12, 0, 11, -2, -12, 0}, \
   {12, -2, -9, 0, 14, -2, -9, 0}, \
   {15, -2, -6, 0, 17, -2, -6, 0}, \
   {18, -2, -3, 0, 20, -2, -3, 0}, \
   {21, -2, 0, 0, 23, -2, 0, 0}, \
}

/// Default audio output gains for analog TV.
#define DEFAULT_CALIB_AUDIO_OUT_TV \
{\
   {0, -2, 0, 0, 2, -2, 0, 0}, \
   {3, -2, -18, 0, 5, -2, -18, 0}, \
   {6, -2, -15, 0, 8, -2, -15, 0}, \
   {9, -2, -12, 0, 11, -2, -12, 0}, \
   {12, -2, -9, 0, 14, -2, -9, 0}, \
   {15, -2, -6, 0, 17, -2, -6, 0}, \
   {18, -2, -3, 0, 20, -2, -3, 0}, \
   {21, -2, 0, 0, 23, -2, 0, 0}, \
}

#endif // AUDIO_CALIB_VER
#endif// 8809 or later
#define SIDE_GAIN CALIB_AUDIO_GAIN_VALUE_MUTE

///  Audio gains, side loop.
#define DEFAULT_CALIB_AUDIO_HS_SIDE   { SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN }
#define DEFAULT_CALIB_AUDIO_EP_SIDE   { SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN }
#define DEFAULT_CALIB_AUDIO_LS_SIDE   { SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN }
#define DEFAULT_CALIB_AUDIO_BT_SIDE   { SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN }
#define DEFAULT_CALIB_AUDIO_FM_SIDE   { SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN }
#define DEFAULT_CALIB_AUDIO_TV_SIDE   { SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN, SIDE_GAIN }




///  Microphone gains parameters
///  { analog gain, ADC gain, algorithm gain }
/// calib_t.bb.audio[itf].audioGains.inGainsCall

#define MIC_GAINS_CALL_HS     { 12, 0, 6 }

#define MIC_GAINS_CALL_EP     { 15, 0, 6 }

#define MIC_GAINS_CALL_LS     { 18, 0, 6 }

#define MIC_GAINS_CALL_BT     { 6, 0, 3 }

#define MIC_GAINS_CALL_FM     { 6, 0, 3 }

#define MIC_GAINS_CALL_TV     { 6, 0, 3 }
/// calib_t.bb.audio[itf].audioGains.inGainsRecord

#define MIC_GAINS_RECORD_HS     { 18, 0, 6 }

#define MIC_GAINS_RECORD_EP     { 18, 0, 6 }

#define MIC_GAINS_RECORD_LS     { 18, 0, 6 }

#define MIC_GAINS_RECORD_BT     { 6, 0, 3 }

#define MIC_GAINS_RECORD_FM     { 6, 0, 3 }

#define MIC_GAINS_RECORD_TV     { 6, 0, 3 }


///  Audio gains parameters, HS
#define DEFAULT_CALIB_AUDIO_GAINS_HS  { MIC_GAINS_CALL_HS, DEFAULT_CALIB_AUDIO_OUT_HS, DEFAULT_CALIB_AUDIO_HS_SIDE, MIC_GAINS_RECORD_HS, }

///  Audio gains parameters, EP
#define DEFAULT_CALIB_AUDIO_GAINS_EP  { MIC_GAINS_CALL_EP, DEFAULT_CALIB_AUDIO_OUT_EP, DEFAULT_CALIB_AUDIO_EP_SIDE, MIC_GAINS_RECORD_EP, }

///  Audio gains parameters, LS
#define DEFAULT_CALIB_AUDIO_GAINS_LS  { MIC_GAINS_CALL_LS, DEFAULT_CALIB_AUDIO_OUT_LS, DEFAULT_CALIB_AUDIO_LS_SIDE, MIC_GAINS_RECORD_LS, }

///  Audio gains parameters, BT
#define DEFAULT_CALIB_AUDIO_GAINS_BT  { MIC_GAINS_CALL_BT, DEFAULT_CALIB_AUDIO_OUT_BT, DEFAULT_CALIB_AUDIO_BT_SIDE, MIC_GAINS_RECORD_BT, }

///  Audio gains parameters, FM
#define DEFAULT_CALIB_AUDIO_GAINS_FM  { MIC_GAINS_CALL_FM, DEFAULT_CALIB_AUDIO_OUT_FM, DEFAULT_CALIB_AUDIO_FM_SIDE, MIC_GAINS_RECORD_FM, }

///  Audio gains parameters, TV
#define DEFAULT_CALIB_AUDIO_GAINS_TV  { MIC_GAINS_CALL_TV, DEFAULT_CALIB_AUDIO_OUT_TV, DEFAULT_CALIB_AUDIO_TV_SIDE, MIC_GAINS_RECORD_TV, }

/// IIR parameters defaults, HS
/// calib_t.iirParam[itf].gain
#define DEFAULT_CALIB_AUDIO_IIR_GAIN_HS  { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
/// calib_t.iirParam[itf].qual
#define DEFAULT_CALIB_AUDIO_IIR_QUAL_HS  { 10, 10, 10, 10, 10, 10, 10, 10, 10, 10}
/// calib_t.iirParam[itf].freq
#define DEFAULT_CALIB_AUDIO_IIR_FREQ_HS  { 38, 77, 115, 191, 268, 345, 490, 600, 1000, 3000}

/// IIR parameters defaults, EP
#define DEFAULT_CALIB_AUDIO_IIR_GAIN_EP  { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define DEFAULT_CALIB_AUDIO_IIR_QUAL_EP  { 10, 10, 10, 10, 10, 10, 10, 10, 10, 10}
#define DEFAULT_CALIB_AUDIO_IIR_FREQ_EP  { 38, 77, 115, 191, 268, 345, 490, 600, 1000, 3000}

/// IIR parameters defaults, LS
#define DEFAULT_CALIB_AUDIO_IIR_GAIN_LS  { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define DEFAULT_CALIB_AUDIO_IIR_QUAL_LS  { 10, 10, 10, 10, 10, 10, 10, 10, 10, 10}
#define DEFAULT_CALIB_AUDIO_IIR_FREQ_LS  { 38, 77, 115, 191, 268, 345, 490, 600, 1000, 3000}

/// IIR parameters defaults, BT
#define DEFAULT_CALIB_AUDIO_IIR_GAIN_BT  { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define DEFAULT_CALIB_AUDIO_IIR_QUAL_BT  { 10, 10, 10, 10, 10, 10, 10, 10, 10, 10}
#define DEFAULT_CALIB_AUDIO_IIR_FREQ_BT  { 38, 77, 115, 191, 268, 345, 490, 600, 1000, 3000}

/// IIR parameters defaults, FM
#define DEFAULT_CALIB_AUDIO_IIR_GAIN_FM  { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define DEFAULT_CALIB_AUDIO_IIR_QUAL_FM  { 10, 10, 10, 10, 10, 10, 10, 10, 10, 10}
#define DEFAULT_CALIB_AUDIO_IIR_FREQ_FM  { 38, 77, 115, 191, 268, 345, 490, 600, 1000, 3000}

/// IIR parameters defaults, TV
#define DEFAULT_CALIB_AUDIO_IIR_GAIN_TV  { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define DEFAULT_CALIB_AUDIO_IIR_QUAL_TV  { 10, 10, 10, 10, 10, 10, 10, 10, 10, 10}
#define DEFAULT_CALIB_AUDIO_IIR_FREQ_TV  { 38, 77, 115, 191, 268, 345, 490, 600, 1000, 3000}

///  IIR parameters, HS
#define DEFAULT_CALIB_AUDIO_IIR_PARAM_HS  { DEFAULT_CALIB_AUDIO_IIR_GAIN_HS, DEFAULT_CALIB_AUDIO_IIR_QUAL_HS, DEFAULT_CALIB_AUDIO_IIR_FREQ_HS, }

///  IIR parameters, EP
#define DEFAULT_CALIB_AUDIO_IIR_PARAM_EP  { DEFAULT_CALIB_AUDIO_IIR_GAIN_EP, DEFAULT_CALIB_AUDIO_IIR_QUAL_EP, DEFAULT_CALIB_AUDIO_IIR_FREQ_EP, }

///  IIR parameters, LS
#define DEFAULT_CALIB_AUDIO_IIR_PARAM_LS  { DEFAULT_CALIB_AUDIO_IIR_GAIN_LS, DEFAULT_CALIB_AUDIO_IIR_QUAL_LS, DEFAULT_CALIB_AUDIO_IIR_FREQ_LS, }

///  IIR parameters, BT
#define DEFAULT_CALIB_AUDIO_IIR_PARAM_BT  { DEFAULT_CALIB_AUDIO_IIR_GAIN_BT, DEFAULT_CALIB_AUDIO_IIR_QUAL_BT, DEFAULT_CALIB_AUDIO_IIR_FREQ_BT, }

///  IIR parameters, FM
#define DEFAULT_CALIB_AUDIO_IIR_PARAM_FM  { DEFAULT_CALIB_AUDIO_IIR_GAIN_FM, DEFAULT_CALIB_AUDIO_IIR_QUAL_FM, DEFAULT_CALIB_AUDIO_IIR_FREQ_FM, }

///  IIR parameters, TV
#define DEFAULT_CALIB_AUDIO_IIR_PARAM_TV  { DEFAULT_CALIB_AUDIO_IIR_GAIN_TV, DEFAULT_CALIB_AUDIO_IIR_QUAL_TV, DEFAULT_CALIB_AUDIO_IIR_FREQ_TV, }

#if (AUDIO_CALIB_VER == 1)
/// calib_t.audio_voc.voc[itf].gain

#define DEFAULT_CALIB_AUDIO_VOC_DIGGAIN_PARAM_HS     { 0x1, 0x1, 0x4000, 0x4000 }

#define DEFAULT_CALIB_AUDIO_VOC_DIGGAIN_PARAM_EP     { 0x1, 0x1, 0x4000, 0x4000 }

#define DEFAULT_CALIB_AUDIO_VOC_DIGGAIN_PARAM_LS     { 0x1, 0x1, 0x4000, 0x4000 }

#define DEFAULT_CALIB_AUDIO_VOC_DIGGAIN_PARAM_BT     { 0x1, 0x1, 0x4000, 0x4000 }

#define DEFAULT_CALIB_AUDIO_VOC_DIGGAIN_PARAM_FM     { 0x1, 0x1, 0x4000, 0x4000 }

#define DEFAULT_CALIB_AUDIO_VOC_DIGGAIN_PARAM_TV     { 0x1, 0x1, 0x4000, 0x4000 }

/// calib_t.audio_voc.voc[itf].hpf
#define DEFAULT_CALIB_AUDIO_IIR_HPF_PARAM_HS     { 1, 0, {{14825, -29650, 14825}, {16384, 29501, -13415}, 0, 2, 180, {0}, {0, 0}} }

#define DEFAULT_CALIB_AUDIO_IIR_HPF_PARAM_EP     { 1, 0, {{14825, -29650, 14825}, {16384, 29501, -13415}, 0, 2, 180, {0}, {0, 0}} }

#define DEFAULT_CALIB_AUDIO_IIR_HPF_PARAM_LS     { 1, 0, {{14825, -29650, 14825}, {16384, 29501, -13415}, 0, 2, 180, {0}, {0, 0}} }

#define DEFAULT_CALIB_AUDIO_IIR_HPF_PARAM_BT     { 1, 0, {{14825, -29650, 14825}, {16384, 29501, -13415}, 0, 2, 180, {0}, {0, 0}} }

#define DEFAULT_CALIB_AUDIO_IIR_HPF_PARAM_FM     { 1, 0, {{14824, -29648, 14824}, {16383, 29499, -13414}, 0, 2, 180, {0}, {0, 0}} }

#define DEFAULT_CALIB_AUDIO_IIR_HPF_PARAM_TV     { 1, 0, {{14824, -29648, 14824}, {16383, 29499, -13414}, 0, 2, 180, {0}, {0, 0}} }
/// calib_t.audio_voc.voc[itf].aec

#define DEFAULT_CALIB_AUDIO_VOC_AEC_PARAM_HS     { 1, 0, 6, 8, 4, 10, 32, 0, 64, 4, 13, 2, 4, 32, 16, 3, 2, 51, 0, 16, 0, 1023, 20, {3, 8, 5, 3, 1, 1, 1, 1, 1}, 0, 0x7f, 128, 64, 160, 4, 256, 128, 64, 6, 160, 16, 16, 115, 64, 0, 71, 35 }

#define DEFAULT_CALIB_AUDIO_VOC_AEC_PARAM_EP     { 1, 0, 6, 8, 4, 10, 32, 0, 64, 4, 13, 2, 4, 32, 16, 3, 2, 51, 0, 16, 0, 1023, 20, {3, 8, 5, 3, 1, 1, 1, 1, 1}, 0, 0x7f, 128, 64, 160, 4, 256, 128, 64, 6, 160, 16, 16, 115, 64, 0, 71, 28 }

#define DEFAULT_CALIB_AUDIO_VOC_AEC_PARAM_LS     { 1, 0, 6, 8, 4, 10, 32, 0, 64, 4, 13, 2, 4, 32, 16, 3, 4, 5, 0, 16, 0, 1023, 20, {1, 1, 1, 1, 1, 1, 1, 1, 1}, 0, 0x7f, 128, 64, 160, 4, 256, 128, 64, 6, 160, 16, 16, 56, 64, 1, 71, 28 }

#define DEFAULT_CALIB_AUDIO_VOC_AEC_PARAM_BT     { 1, 0, 6, 8, 4, 10, 32, 0, 64, 4, 13, 2, 4, 32, 16, 3, 2, 51, 0, 16, 0, 1023, 20, {3, 8, 5, 3, 1, 1, 1, 1, 1}, 0, 0x7f, 128, 64, 160, 4, 256, 128, 64, 6, 160, 16, 16, 115, 64, 0, 71, 35 }

#define DEFAULT_CALIB_AUDIO_VOC_AEC_PARAM_FM     { 1, 0, 6, 8, 4, 10, 32, 0, 64, 4, 13, 1, 40, 32, 16, 3, 2, 51, 0, 16, 0, 1023, 20, {3, 8, 5, 3, 1, 1, 1, 1, 1}, 0, 0x7f, 128, 64, 160, 4, 256, 128, 64, 6, 160, 16, 16, 115, 64, 0, 71, 35 }

#define DEFAULT_CALIB_AUDIO_VOC_AEC_PARAM_TV     { 1, 0, 6, 8, 4, 10, 32, 0, 64, 4, 13, 1, 40, 32, 16, 3, 2, 51, 0, 16, 0, 1023, 20, {3, 8, 5, 3, 1, 1, 1, 1, 1}, 0, 0x7f, 128, 64, 160, 4, 256, 128, 64, 6, 160, 16, 16, 115, 64, 0, 71, 35 }

/// calib_t.audio_voc.voc[itf].speex

#define DEFAULT_CALIB_AUDIO_VOC_SPEEX_PARAM_HS  \
{\
{0, -30, {30, 30, 30, 30}, {0, 0} },\
{0, -30, {30, 30, 30, 30}, {0, 0} },\
}

#define DEFAULT_CALIB_AUDIO_VOC_SPEEX_PARAM_EP  \
{\
{0, -30, {30, 30, 30, 30}, {0, 0} },\
{0, -30, {30, 30, 30, 30}, {0, 0} },\
}

#define DEFAULT_CALIB_AUDIO_VOC_SPEEX_PARAM_LS  \
{\
{0, -30, {30, 30, 30, 30}, {0, 0} },\
{0, -30, {30, 30, 30, 30}, {0, 0} },\
}

#define DEFAULT_CALIB_AUDIO_VOC_SPEEX_PARAM_BT  \
{\
{0, -30, {30, 30, 30, 30}, {0, 0} },\
{0, -30, {30, 30, 30, 30}, {0, 0} },\
}

#define DEFAULT_CALIB_AUDIO_VOC_SPEEX_PARAM_FM  \
{\
{0, -30, {30, 30, 30, 30}, {0, 0} },\
{1, -30, {30, 30, 30, 30}, {0, 0} },\
}

#define DEFAULT_CALIB_AUDIO_VOC_SPEEX_PARAM_TV  \
{\
{0, -30, {30, 30, 30, 30}, {0, 0} },\
{1, -30, {30, 30, 30, 30}, {0, 0} },\
}

/// calib_t.audio_voc.voc[itf].agc

#define DEFAULT_CALIB_AUDIO_VOC_AGC_PARAM_HS  \
{\
{1, 100, 0, 0x6},\
{1, 500, 300, 0x6},\
}

#define DEFAULT_CALIB_AUDIO_VOC_AGC_PARAM_EP  \
{\
{1, 100, 0, 0x9},\
{0, 200, 100, 0x6},\
}

#define DEFAULT_CALIB_AUDIO_VOC_AGC_PARAM_LS  \
{\
{1, 100, 0, 0x9},\
{1, 500, 300, 0x6},\
}

#define DEFAULT_CALIB_AUDIO_VOC_AGC_PARAM_BT  \
{\
{0, 1000, 700, 0x6},\
{1, 500, 300, 0x6},\
}

#define DEFAULT_CALIB_AUDIO_VOC_AGC_PARAM_FM  \
{\
{0, 1000, 700, 0x6},\
{1, 1000, 700, 0x6},\
}

#define DEFAULT_CALIB_AUDIO_VOC_AGC_PARAM_TV  \
{\
{0, 1000, 700, 0x6},\
{1, 1000, 700, 0x6},\
}

/// calib_t.audio_voc.voc[itf].eq

#define DEFAULT_CALIB_AUDIO_VOC_IIR_EQ_PARAM_HS  \
{\
0,\
0,\
{\
{{0x3afe, 0x8a05, 0x3afe}, {0x4000, 0x7540, 0xc949}, 0, 2, 200, {10}, {10, 10}},\
{{0x4000, 0x9690, 0x2edf}, {0x4000, 0x6970, 0xd121}, 0, 3, 400, {10}, {10, 10}},\
{{0x4000, 0xa30e, 0x2852}, {0x4000, 0x5cf2, 0xd7ae}, 0, 3, 600, {10}, {10, 10}},\
{{0x4000, 0xaff9, 0x22ed}, {0x4000, 0x5007, 0xdd13}, 0, 3, 800, {10}, {10, 10}},\
{{0x4000, 0xbd23, 0x1e91}, {0x4000, 0x42dd, 0xe16f}, 0, 3, 1000, {10}, {10, 10}},\
{{0x4000, 0xe532, 0x16c0}, {0x4000, 0x1ace, 0xe940}, 0, 3, 1600, {10}, {10, 10}},\
{{0x3988, 0x6afc, 0x338c}, {0x4000, 0x9504, 0xd2ec}, 0, 1, 3750, {10}, {10, 10}},\
}\
}

#define DEFAULT_CALIB_AUDIO_VOC_IIR_EQ_PARAM_EP  \
{\
0,\
0,\
{\
{{0x3afe, 0x8a05, 0x3afe}, {0x4000, 0x7540, 0xc949}, 0, 2, 200, {10}, {10, 10}},\
{{0x4000, 0x9690, 0x2edf}, {0x4000, 0x6970, 0xd121}, 0, 3, 400, {10}, {10, 10}},\
{{0x4000, 0xa30e, 0x2852}, {0x4000, 0x5cf2, 0xd7ae}, 0, 3, 600, {10}, {10, 10}},\
{{0x4000, 0xaff9, 0x22ed}, {0x4000, 0x5007, 0xdd13}, 0, 3, 800, {10}, {10, 10}},\
{{0x4000, 0xbd23, 0x1e91}, {0x4000, 0x42dd, 0xe16f}, 0, 3, 1000, {10}, {10, 10}},\
{{0x4000, 0xe532, 0x16c0}, {0x4000, 0x1ace, 0xe940}, 0, 3, 1600, {10}, {10, 10}},\
{{0x3988, 0x6afc, 0x338c}, {0x4000, 0x9504, 0xd2ec}, 0, 1, 3750, {10}, {10, 10}},\
}\
}

#define DEFAULT_CALIB_AUDIO_VOC_IIR_EQ_PARAM_LS  \
{\
1,\
0,\
{\
{{0x3073, 0x9f19, 0x3073}, {0x4000, 0x5d12, 0xdb43}, 0, 2, 500, {7}, {0, 0}},\
{{0x4000, 0x0000, 0x0000}, {0x4000, 0x0000, 0x0000}, 0, 0, 150, {7}, {0, 0}},\
{{0x4000, 0x0000, 0x0000}, {0x4000, 0x0000, 0x0000}, 0, 0, 200, {7}, {0, 0}},\
{{0x4000, 0x0000, 0x0000}, {0x4000, 0x0000, 0x0000}, 0, 0, 400, {7}, {0, 0}},\
{{0x4000, 0x0000, 0x0000}, {0x4000, 0x0000, 0x0000}, 0, 0, 1000, {7}, {0, 0}},\
{{0x4000, 0x0000, 0x0000}, {0x4000, 0x0000, 0x0000}, 0, 0, 2000, {7}, {0, 0}},\
{{0x37b3, 0x6f66, 0x37b3}, {0x4000, 0x91ae, 0xcf85}, 0, 1, 3750, {7}, {0, 0}},\
}\
}

#define DEFAULT_CALIB_AUDIO_VOC_IIR_EQ_PARAM_BT  \
{\
0,\
0,\
{\
{{0x3afe, 0x8a05, 0x3afe}, {0x4000, 0x7540, 0xc949}, 0, 2, 200, {10}, {10, 10}},\
{{0x4000, 0x9690, 0x2edf}, {0x4000, 0x6970, 0xd121}, 0, 3, 400, {10}, {10, 10}},\
{{0x4000, 0xa30e, 0x2852}, {0x4000, 0x5cf2, 0xd7ae}, 0, 3, 600, {10}, {10, 10}},\
{{0x4000, 0xaff9, 0x22ed}, {0x4000, 0x5007, 0xdd13}, 0, 3, 800, {10}, {10, 10}},\
{{0x4000, 0xbd23, 0x1e91}, {0x4000, 0x42dd, 0xe16f}, 0, 3, 1000, {10}, {10, 10}},\
{{0x4000, 0xe532, 0x16c0}, {0x4000, 0x1ace, 0xe940}, 0, 3, 1600, {10}, {10, 10}},\
{{0x3988, 0x6afc, 0x338c}, {0x4000, 0x9504, 0xd2ec}, 0, 1, 3750, {10}, {10, 10}},\
}\
}

#define DEFAULT_CALIB_AUDIO_VOC_IIR_EQ_PARAM_FM  \
{\
0,\
0,\
{\
{{0x3afe, 0x8a05, 0x3afe}, {0x4000, 0x7540, 0xc949}, 0, 2, 200, {10}, {10, 10}},\
{{0x4000, 0x9690, 0x2edf}, {0x4000, 0x6970, 0xd121}, 0, 3, 400, {10}, {10, 10}},\
{{0x4000, 0xa30e, 0x2852}, {0x4000, 0x5cf2, 0xd7ae}, 0, 3, 600, {10}, {10, 10}},\
{{0x4000, 0xaff9, 0x22ed}, {0x4000, 0x5007, 0xdd13}, 0, 3, 800, {10}, {10, 10}},\
{{0x4000, 0xbd23, 0x1e91}, {0x4000, 0x42dd, 0xe16f}, 0, 3, 1000, {10}, {10, 10}},\
{{0x4000, 0xe532, 0x16c0}, {0x4000, 0x1ace, 0xe940}, 0, 3, 1600, {10}, {10, 10}},\
{{0x3988, 0x6afc, 0x338c}, {0x4000, 0x9504, 0xd2ec}, 0, 1, 3750, {10}, {10, 10}},\
}\
}

#define DEFAULT_CALIB_AUDIO_VOC_IIR_EQ_PARAM_TV  \
{\
0,\
0,\
{\
{{0x3afe, 0x8a05, 0x3afe}, {0x4000, 0x7540, 0xc949}, 0, 2, 200, {10}, {10, 10}},\
{{0x4000, 0x9690, 0x2edf}, {0x4000, 0x6970, 0xd121}, 0, 3, 400, {10}, {10, 10}},\
{{0x4000, 0xa30e, 0x2852}, {0x4000, 0x5cf2, 0xd7ae}, 0, 3, 600, {10}, {10, 10}},\
{{0x4000, 0xaff9, 0x22ed}, {0x4000, 0x5007, 0xdd13}, 0, 3, 800, {10}, {10, 10}},\
{{0x4000, 0xbd23, 0x1e91}, {0x4000, 0x42dd, 0xe16f}, 0, 3, 1000, {10}, {10, 10}},\
{{0x4000, 0xe532, 0x16c0}, {0x4000, 0x1ace, 0xe940}, 0, 3, 1600, {10}, {10, 10}},\
{{0x3988, 0x6afc, 0x338c}, {0x4000, 0x9504, 0xd2ec}, 0, 1, 3750, {10}, {10, 10}},\
}\
}

#define DEFAULT_CALIB_AUDIO_VOC_MP3_PARAM_HS  \
{\
0x0000, 0x0000,\
{0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0002, 0x0002, 0x0002, 0x0004,\
0x0004, 0x0004, 0x0004, 0x0004,\
0x0004, 0x0008, 0x0008, 0x0008,\
0x0008, 0x0008, 0x0008, 0x0010,\
0x0010, 0x0010, 0x0010, 0x0010,\
0x0020, 0x0020, 0x0020, 0x0020,\
0x0020, 0x0040, 0x0040, 0x0040,\
0x003f, 0x0000, 0x0000, 0x0000} }

#define DEFAULT_CALIB_AUDIO_VOC_MP3_PARAM_EP  \
{\
0x0000, 0x0000,\
{0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0002, 0x0002, 0x0002, 0x0004,\
0x0004, 0x0004, 0x0004, 0x0004,\
0x0004, 0x0008, 0x0008, 0x0008,\
0x0008, 0x0008, 0x0008, 0x0010,\
0x0010, 0x0010, 0x0010, 0x0010,\
0x0020, 0x0020, 0x0020, 0x0020,\
0x0020, 0x0040, 0x0040, 0x0040,\
0x003f, 0x0000, 0x0000, 0x0000} }

#define DEFAULT_CALIB_AUDIO_VOC_MP3_PARAM_LS  \
{\
0x0000, 0x0000,\
{0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0002, 0x0002, 0x0002, 0x0004,\
0x0004, 0x0004, 0x0004, 0x0004,\
0x0004, 0x0008, 0x0008, 0x0008,\
0x0008, 0x0008, 0x0008, 0x0010,\
0x0010, 0x0010, 0x0010, 0x0010,\
0x0020, 0x0020, 0x0020, 0x0020,\
0x0020, 0x0040, 0x0040, 0x0040,\
0x003f, 0x0000, 0x0000, 0x0000} }

#define DEFAULT_CALIB_AUDIO_VOC_MP3_PARAM_BT  \
{\
0x0000, 0x0000,\
{0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0002, 0x0002, 0x0002, 0x0004,\
0x0004, 0x0004, 0x0004, 0x0004,\
0x0004, 0x0008, 0x0008, 0x0008,\
0x0008, 0x0008, 0x0008, 0x0010,\
0x0010, 0x0010, 0x0010, 0x0010,\
0x0020, 0x0020, 0x0020, 0x0020,\
0x0020, 0x0040, 0x0040, 0x0040,\
0x003f, 0x0000, 0x0000, 0x0000} }

#define DEFAULT_CALIB_AUDIO_VOC_MP3_PARAM_FM  \
{\
0x0000, 0x0000,\
{0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0002, 0x0002, 0x0002, 0x0004,\
0x0004, 0x0004, 0x0004, 0x0004,\
0x0004, 0x0008, 0x0008, 0x0008,\
0x0008, 0x0008, 0x0008, 0x0010,\
0x0010, 0x0010, 0x0010, 0x0010,\
0x0020, 0x0020, 0x0020, 0x0020,\
0x0020, 0x0040, 0x0040, 0x0040,\
0x003f, 0x0000, 0x0000, 0x0000} }

#define DEFAULT_CALIB_AUDIO_VOC_MP3_PARAM_TV  \
{\
0x0000, 0x0000,\
{0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0400, 0x0400, 0x0400, 0x0400,\
0x0002, 0x0002, 0x0002, 0x0004,\
0x0004, 0x0004, 0x0004, 0x0004,\
0x0004, 0x0008, 0x0008, 0x0008,\
0x0008, 0x0008, 0x0008, 0x0010,\
0x0010, 0x0010, 0x0010, 0x0010,\
0x0020, 0x0020, 0x0020, 0x0020,\
0x0020, 0x0040, 0x0040, 0x0040,\
0x003f, 0x0000, 0x0000, 0x0000} }

#define DEFAULT_CALIB_AUDIO_VOC_PARAM_HS  \
{\
DEFAULT_CALIB_AUDIO_VOC_DIGGAIN_PARAM_HS, \
DEFAULT_CALIB_AUDIO_IIR_HPF_PARAM_HS, \
DEFAULT_CALIB_AUDIO_VOC_AEC_PARAM_HS, \
DEFAULT_CALIB_AUDIO_VOC_SPEEX_PARAM_HS, \
DEFAULT_CALIB_AUDIO_VOC_AGC_PARAM_HS, \
DEFAULT_CALIB_AUDIO_VOC_HS_FILTERS, \
DEFAULT_CALIB_AUDIO_VOC_IIR_EQ_PARAM_HS, \
 DEFAULT_CALIB_AUDIO_VOC_MP3_PARAM_HS, \
}

#define DEFAULT_CALIB_AUDIO_VOC_PARAM_EP  \
{\
DEFAULT_CALIB_AUDIO_VOC_DIGGAIN_PARAM_EP, \
DEFAULT_CALIB_AUDIO_IIR_HPF_PARAM_EP, \
DEFAULT_CALIB_AUDIO_VOC_AEC_PARAM_EP, \
DEFAULT_CALIB_AUDIO_VOC_SPEEX_PARAM_EP, \
DEFAULT_CALIB_AUDIO_VOC_AGC_PARAM_EP, \
DEFAULT_CALIB_AUDIO_VOC_EP_FILTERS, \
DEFAULT_CALIB_AUDIO_VOC_IIR_EQ_PARAM_EP, \
 DEFAULT_CALIB_AUDIO_VOC_MP3_PARAM_EP, \
}

#define DEFAULT_CALIB_AUDIO_VOC_PARAM_LS  \
{\
DEFAULT_CALIB_AUDIO_VOC_DIGGAIN_PARAM_LS, \
DEFAULT_CALIB_AUDIO_IIR_HPF_PARAM_LS, \
DEFAULT_CALIB_AUDIO_VOC_AEC_PARAM_LS, \
DEFAULT_CALIB_AUDIO_VOC_SPEEX_PARAM_LS, \
DEFAULT_CALIB_AUDIO_VOC_AGC_PARAM_LS, \
DEFAULT_CALIB_AUDIO_VOC_LS_FILTERS, \
DEFAULT_CALIB_AUDIO_VOC_IIR_EQ_PARAM_LS, \
 DEFAULT_CALIB_AUDIO_VOC_MP3_PARAM_LS, \
}

#define DEFAULT_CALIB_AUDIO_VOC_PARAM_BT  \
{\
DEFAULT_CALIB_AUDIO_VOC_DIGGAIN_PARAM_BT, \
DEFAULT_CALIB_AUDIO_IIR_HPF_PARAM_BT, \
DEFAULT_CALIB_AUDIO_VOC_AEC_PARAM_BT, \
DEFAULT_CALIB_AUDIO_VOC_SPEEX_PARAM_BT, \
DEFAULT_CALIB_AUDIO_VOC_AGC_PARAM_BT, \
DEFAULT_CALIB_AUDIO_VOC_BT_FILTERS, \
DEFAULT_CALIB_AUDIO_VOC_IIR_EQ_PARAM_BT, \
 DEFAULT_CALIB_AUDIO_VOC_MP3_PARAM_BT, \
}

#define DEFAULT_CALIB_AUDIO_VOC_PARAM_FM  \
{\
DEFAULT_CALIB_AUDIO_VOC_DIGGAIN_PARAM_FM, \
DEFAULT_CALIB_AUDIO_IIR_HPF_PARAM_FM, \
DEFAULT_CALIB_AUDIO_VOC_AEC_PARAM_FM, \
DEFAULT_CALIB_AUDIO_VOC_SPEEX_PARAM_FM, \
DEFAULT_CALIB_AUDIO_VOC_AGC_PARAM_FM, \
DEFAULT_CALIB_AUDIO_VOC_FM_FILTERS, \
DEFAULT_CALIB_AUDIO_VOC_IIR_EQ_PARAM_FM, \
 DEFAULT_CALIB_AUDIO_VOC_MP3_PARAM_FM, \
}

#define DEFAULT_CALIB_AUDIO_VOC_PARAM_TV  \
{\
DEFAULT_CALIB_AUDIO_VOC_DIGGAIN_PARAM_TV, \
DEFAULT_CALIB_AUDIO_IIR_HPF_PARAM_TV, \
DEFAULT_CALIB_AUDIO_VOC_AEC_PARAM_TV, \
DEFAULT_CALIB_AUDIO_VOC_SPEEX_PARAM_TV, \
DEFAULT_CALIB_AUDIO_VOC_AGC_PARAM_TV, \
DEFAULT_CALIB_AUDIO_VOC_TV_FILTERS, \
DEFAULT_CALIB_AUDIO_VOC_IIR_EQ_PARAM_TV, \
 DEFAULT_CALIB_AUDIO_VOC_MP3_PARAM_TV, \
}

// FOR AP
/// calib_t.audio_music.music[itf].eq

#define DEFAULT_CALIB_AUDIO_MUSIC_IIR_EQ_PARAM_HS  \
{\
0,\
0,\
{\
{{0x3f17, 0x81d4, 0x3f17}, {0x4000, 0x7e26, 0xc1cc}, 0, 2, 200, {10}, {10, 10}},\
{{0x4000, 0x83c0, 0x3c75}, {0x4000, 0x7c40, 0xc38b}, 0, 3, 400, {10}, {10, 10}},\
{{0x4000, 0x85b1, 0x3ac2}, {0x4000, 0x7a4f, 0xc53e}, 0, 3, 600, {10}, {10, 10}},\
{{0x4000, 0x87ad, 0x391d}, {0x4000, 0x7853, 0xc6e3}, 0, 3, 800, {10}, {10, 10}},\
{{0x4000, 0x89b3, 0x3784}, {0x4000, 0x764e, 0xc87c}, 0, 3, 1000, {10}, {10, 10}},\
{{0x4000, 0x8ff9, 0x3301}, {0x4000, 0x7007, 0xccff}, 0, 3, 1600, {10}, {10, 10}},\
{{0x4000, 0x944e, 0x303a}, {0x4000, 0x6bb2, 0xcfc6}, 0, 3, 2000, {10}, {10, 10}},\
}\
}

#define DEFAULT_CALIB_AUDIO_MUSIC_IIR_EQ_PARAM_EP  \
{\
0,\
0,\
{\
{{0x3f17, 0x81d4, 0x3f17}, {0x4000, 0x7e26, 0xc1cc}, 0, 2, 200, {10}, {10, 10}},\
{{0x4000, 0x83c0, 0x3c75}, {0x4000, 0x7c40, 0xc38b}, 0, 3, 400, {10}, {10, 10}},\
{{0x4000, 0x85b1, 0x3ac2}, {0x4000, 0x7a4f, 0xc53e}, 0, 3, 600, {10}, {10, 10}},\
{{0x4000, 0x87ad, 0x391d}, {0x4000, 0x7853, 0xc6e3}, 0, 3, 800, {10}, {10, 10}},\
{{0x4000, 0x89b3, 0x3784}, {0x4000, 0x764e, 0xc87c}, 0, 3, 1000, {10}, {10, 10}},\
{{0x4000, 0x8ff9, 0x3301}, {0x4000, 0x7007, 0xccff}, 0, 3, 1600, {10}, {10, 10}},\
{{0x4000, 0x944e, 0x303a}, {0x4000, 0x6bb2, 0xcfc6}, 0, 3, 2000, {10}, {10, 10}},\
}\
}

#define DEFAULT_CALIB_AUDIO_MUSIC_IIR_EQ_PARAM_LS  \
{\
1,\
0,\
{\
{{0x3ba4, 0x88b8, 0x3ba4}, {0x4000, 0x76fc, 0xc86c}, 0, 2, 700, {7}, {10, 10}},\
{{0x4000, 0x0000, 0x0000}, {0x4000, 0x0000, 0x0000}, 0, 0, 150, {7}, {10, 10}},\
{{0x4000, 0x0000, 0x0000}, {0x4000, 0x0000, 0x0000}, 0, 0, 200, {7}, {10, 10}},\
{{0x4000, 0x0000, 0x0000}, {0x4000, 0x0000, 0x0000}, 0, 0, 400, {7}, {10, 10}},\
{{0x4000, 0x0000, 0x0000}, {0x4000, 0x0000, 0x0000}, 0, 0, 1000, {7}, {10, 10}},\
{{0x4000, 0x0000, 0x0000}, {0x4000, 0x0000, 0x0000}, 0, 0, 2000, {7}, {10, 10}},\
{{0x1016, 0x202d, 0x1016}, {0x4000, 0x0af5, 0xf4b0}, 0, 1, 10000, {7}, {10, 10}},\
}\
}

#define DEFAULT_CALIB_AUDIO_MUSIC_IIR_EQ_PARAM_BT  \
{\
0,\
0,\
{\
{{0x3f17, 0x81d4, 0x3f17}, {0x4000, 0x7e26, 0xc1cc}, 0, 2, 200, {10}, {10, 10}},\
{{0x4000, 0x83c0, 0x3c75}, {0x4000, 0x7c40, 0xc38b}, 0, 3, 400, {10}, {10, 10}},\
{{0x4000, 0x85b1, 0x3ac2}, {0x4000, 0x7a4f, 0xc53e}, 0, 3, 600, {10}, {10, 10}},\
{{0x4000, 0x87ad, 0x391d}, {0x4000, 0x7853, 0xc6e3}, 0, 3, 800, {10}, {10, 10}},\
{{0x4000, 0x89b3, 0x3784}, {0x4000, 0x764e, 0xc87c}, 0, 3, 1000, {10}, {10, 10}},\
{{0x4000, 0x8ff9, 0x3301}, {0x4000, 0x7007, 0xccff}, 0, 3, 1600, {10}, {10, 10}},\
{{0x4000, 0x944e, 0x303a}, {0x4000, 0x6bb2, 0xcfc6}, 0, 3, 2000, {10}, {10, 10}},\
}\
}

#define DEFAULT_CALIB_AUDIO_MUSIC_IIR_EQ_PARAM_FM  \
{\
0,\
0,\
{\
{{0x3f17, 0x81d4, 0x3f17}, {0x4000, 0x7e26, 0xc1cc}, 0, 2, 200, {10}, {10, 10}},\
{{0x4000, 0x83c0, 0x3c75}, {0x4000, 0x7c40, 0xc38b}, 0, 3, 400, {10}, {10, 10}},\
{{0x4000, 0x85b1, 0x3ac2}, {0x4000, 0x7a4f, 0xc53e}, 0, 3, 600, {10}, {10, 10}},\
{{0x4000, 0x87ad, 0x391d}, {0x4000, 0x7853, 0xc6e3}, 0, 3, 800, {10}, {10, 10}},\
{{0x4000, 0x89b3, 0x3784}, {0x4000, 0x764e, 0xc87c}, 0, 3, 1000, {10}, {10, 10}},\
{{0x4000, 0x8ff9, 0x3301}, {0x4000, 0x7007, 0xccff}, 0, 3, 1600, {10}, {10, 10}},\
{{0x4000, 0x944e, 0x303a}, {0x4000, 0x6bb2, 0xcfc6}, 0, 3, 2000, {10}, {10, 10}},\
}\
}

#define DEFAULT_CALIB_AUDIO_MUSIC_IIR_EQ_PARAM_TV  \
{\
0,\
0,\
{\
{{0x3f17, 0x81d4, 0x3f17}, {0x4000, 0x7e26, 0xc1cc}, 0, 2, 200, {10}, {10, 10}},\
{{0x4000, 0x83c0, 0x3c75}, {0x4000, 0x7c40, 0xc38b}, 0, 3, 400, {10}, {10, 10}},\
{{0x4000, 0x85b1, 0x3ac2}, {0x4000, 0x7a4f, 0xc53e}, 0, 3, 600, {10}, {10, 10}},\
{{0x4000, 0x87ad, 0x391d}, {0x4000, 0x7853, 0xc6e3}, 0, 3, 800, {10}, {10, 10}},\
{{0x4000, 0x89b3, 0x3784}, {0x4000, 0x764e, 0xc87c}, 0, 3, 1000, {10}, {10, 10}},\
{{0x4000, 0x8ff9, 0x3301}, {0x4000, 0x7007, 0xccff}, 0, 3, 1600, {10}, {10, 10}},\
{{0x4000, 0x944e, 0x303a}, {0x4000, 0x6bb2, 0xcfc6}, 0, 3, 2000, {10}, {10, 10}},\
}\
}

/// calib_t.audio_music.music[itf].drc

#define DEFAULT_CALIB_AUDIO_MUSIC_DRC_PARAM_HS   { 0, -3840, 3072, 1, 1, 3, -768, 1536, 33, 16, -17920, 1638, -3, 0, 2, 0 }

#define DEFAULT_CALIB_AUDIO_MUSIC_DRC_PARAM_EP   { 1, -3840, 3072, 1, 1, 3, -768, 1536, 33, 16, -17920, 1638, -1, 0, 2, 0 }

#define DEFAULT_CALIB_AUDIO_MUSIC_DRC_PARAM_LS   { 1, -3840, 3072, 1, 1, 3, -768, 1536, 33, 16, -17920, 1638, -1, 0, 2, 0 }

#define DEFAULT_CALIB_AUDIO_MUSIC_DRC_PARAM_BT   { 0, -3840, 3072, 1, 1, 3, -768, 1536, 33, 16, -17920, 1638, -3, 0, 2, 0 }

#define DEFAULT_CALIB_AUDIO_MUSIC_DRC_PARAM_FM   { 0, -3840, 3072, 1, 1, 3, -768, 1536, 33, 16, -17920, 1638, -3, 0, 2, 0 }

#define DEFAULT_CALIB_AUDIO_MUSIC_DRC_PARAM_TV   { 0, -3840, 3072, 1, 1, 3, -768, 1536, 33, 16, -17920, 1638, -3, 0, 2, 0 }

#define DEFAULT_CALIB_AUDIO_MUSIC_PARAM_HS   {DEFAULT_CALIB_AUDIO_MUSIC_IIR_EQ_PARAM_HS, DEFAULT_CALIB_AUDIO_MUSIC_DRC_PARAM_HS}

#define DEFAULT_CALIB_AUDIO_MUSIC_PARAM_EP   {DEFAULT_CALIB_AUDIO_MUSIC_IIR_EQ_PARAM_EP, DEFAULT_CALIB_AUDIO_MUSIC_DRC_PARAM_EP}

#define DEFAULT_CALIB_AUDIO_MUSIC_PARAM_LS   {DEFAULT_CALIB_AUDIO_MUSIC_IIR_EQ_PARAM_LS, DEFAULT_CALIB_AUDIO_MUSIC_DRC_PARAM_LS}

#define DEFAULT_CALIB_AUDIO_MUSIC_PARAM_BT   {DEFAULT_CALIB_AUDIO_MUSIC_IIR_EQ_PARAM_BT, DEFAULT_CALIB_AUDIO_MUSIC_DRC_PARAM_BT}

#define DEFAULT_CALIB_AUDIO_MUSIC_PARAM_FM   {DEFAULT_CALIB_AUDIO_MUSIC_IIR_EQ_PARAM_FM, DEFAULT_CALIB_AUDIO_MUSIC_DRC_PARAM_FM}

#define DEFAULT_CALIB_AUDIO_MUSIC_PARAM_TV   {DEFAULT_CALIB_AUDIO_MUSIC_IIR_EQ_PARAM_TV, DEFAULT_CALIB_AUDIO_MUSIC_DRC_PARAM_TV}

#endif

#endif //  _CALIBP_AUDIO_DEFAULTS_H_ 
