# flash config
BOARD_NAND_PAGE_SIZE := 4096
BOARD_NAND_SPARE_SIZE := 128
BOARD_FLASH_BLOCK_SIZE := 1048576

# touch screen selection
RDA_CUSTOMER_DRV_TS := TS_GSL168X
#  GSL168X_MODEL := GSL168X_MODEL_35_HVGA_1680
#  GSL168X_MODEL := GSL168X_MODEL_35_HVGA_1688E
#  GSL168X_MODEL := GSL168X_MODEL_40_WVGA
#  GSL168X_MODEL := GSL168X_MODEL_70_WVGAL
GSL168X_MODEL := GSL168X_MODEL_WVGA_X3
# RDA_CUSTOMER_DRV_TS := TS_MSG2133
# RDA_CUSTOMER_DRV_TS := TS_FT6X06
# RDA_CUSTOMER_DRV_TS := TS_IT7252
# RDA_CUSTOMER_DRV_TS := TS_GTP868
# RDA_CUSTOMER_DRV_TS := TS_ICN831X

# gsensor selection
RDA_CUSTOMER_DRV_GS := GS_MC3XXX
# RDA_CUSTOMER_DRV_GS := GS_MMA845X
# RDA_CUSTOMER_DRV_GS := GS_MMA865X
# RDA_CUSTOMER_DRV_GS := GS_MMA7660
# RDA_CUSTOMER_DRV_GS := GS_STK8312

# light sensor selection
RDA_CUSTOMER_DRV_LS := LS_TAOS2771X

#camera sensor selection
# supported list in device/rda/driver/camera/inc/
RDA_CUSTOMER_DRV_CSB := GC2035
RDA_CUSTOMER_DRV_CSF := GC0308

export RDA_CUSTOMER_DRV_TS
ifeq ($(RDA_CUSTOMER_DRV_TS), TS_GSL168X)
export GSL168X_MODEL
endif
export RDA_CUSTOMER_DRV_GS
export RDA_CUSTOMER_DRV_LS
export RDA_CUSTOMER_DRV_CSB
export RDA_CUSTOMER_DRV_CSF

